### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by lucas794** [ftrelz/Keyboard-Equalizer#1]
Hi! I'm trying hard to compile on Ubuntu, but i'm not able to do it.

Which line do you use for compiling whole project? I own a K70 LUX RGB hope this works!

**Comment by ftrelz** [comment]
Hi Lucas. Unfortunately I wrote this using the Visual C++ compiler and using the Windows API so as far as I know there is no easy way to get this code to compile on a Linux system. If you would really like to get this to work you could try to replace the Windows specific code with it's POSIX/UNIX equivalent.

**Comment by lucas794** [comment]
Fantastic, thanks so much for the info! I know how to programming, but well, no one talks about which program to compile! Thanks so much for the info!
